language: php

cache:
  directories:
  - "$HOME/.composer/cache"

php:
    - '7.1'
    - '7.2'
    - '7.3'

env:
    - LARAVEL=5.5
    - LARAVEL=5.6
    - LARAVEL=5.7
    - LARAVEL=5.8
    - LARAVEL=6.0
    - LARAVEL=6.5

matrix:
  exclude:
    - php: '7.1'
      env: 'LARAVEL=6.0'
    - php: '7.1'
      env: 'LARAVEL=6.5'

script:
- vendor/bin/phpunit

before_install:
- MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
- '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
- '[ 6 -eq $MAJOR ] && ORCH=4 || ORCH=3'
- composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
- composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "MudaWji89kwJGrpKIr6ql6EdpLx7pheB8ag/bL6HdVd7GedR1MJFTMNlQWzzE21URUMfeKOBYE5htnsKUlLZBRX5QHQoNml7IAXZlA5zqqLGp28aOOLJxpIsZ2UVx5QHa6FQOA9X5XKwN16EdIFO840sx6WvWF1ZzEzWzsJmRw0zIlMCnPZr0/wRglnN/ShuH44j/o/QVHGW5DyNZo8CYFs0KKAbEdxJ+dVebrq3dExsjqRQsQnOdKj/ikYuVcxbxtggq2nSifZth3axb7hzSAR7QieDQvehZykeMFYNNEBzl2z8oM8dQxHl6uutpd0J6uX6cnNnZlyE+rZUo6QsXO7+CdyIa3G2M+ru6EDWd7klEoFWh5Ho5sE0EqgCW4vvWrjHV9EwjyPyeNB3BPlbmmAr6sGR46mBAV8oDXooc8INJhbGQvYJF0TvCjxQ/BFLQnlYMJ+nbtUGMSPFOGcYQD8JzOFaA+YSXbczLaYZtYErrunBNtff66ucFrdi1d4WYe3HuzOr0nrgvkobCxKoyU2Q7q3EhMPmx1S+m4JLbZo+8dxpbpeh1AyQD4jY8Ob9sIARkI4XyHhE7LFHbmj9W/4tQu6McwfnqVt6IgaAG5/LE5xoN2UPoeQYJphQ/q3DIxpBqgd5WxY3t/PIVM8QTel1jzJSHcEdAAl3ljQ9WGc="
