version: "3.3"

services:
  appshell_test_php80:
    image: php:8.0-cli-alpine
    volumes:
      - .:/build
  appshell_test_php81:
    image: phpdaily/php:8.1.0-dev-cli-alpine3.12
    volumes:
      - .:/build
